"""empty message

Revision ID: 2b9be79304a1
Revises: dd5f3b5e2ef4
Create Date: 2023-08-20 22:09:41.732483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9be79304a1'
down_revision = 'dd5f3b5e2ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.drop_constraint('cart_products_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cart_products_cart_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'shopping_carts', ['cart_id'], ['id'])

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('recipient_phone_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('recipient_phone_number')
        batch_op.drop_column('recipient_email')

    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cart_products_cart_id_fkey', 'shopping_carts', ['cart_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('cart_products_product_id_fkey', 'products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
