"""empty message

Revision ID: 2f16cf4fb953
Revises: 954152d1c4c4
Create Date: 2023-08-07 21:03:21.533435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f16cf4fb953'
down_revision = '954152d1c4c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('shipping_type_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('payment_type_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint('order_details_shipping_type_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_details_payment_type_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'shipping_types', ['shipping_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'payment_types', ['payment_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])
        batch_op.drop_column('currency')
        batch_op.drop_column('shipping_type')
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shipping_type', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('currency', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_details_payment_type_fkey', 'payment_types', ['payment_type'], ['id'])
        batch_op.create_foreign_key('order_details_shipping_type_fkey', 'shipping_types', ['shipping_type'], ['id'])
        batch_op.drop_column('payment_type_id')
        batch_op.drop_column('shipping_type_id')
        batch_op.drop_column('currency_id')

    # ### end Alembic commands ###
