"""empty message

Revision ID: 5d4fc0e4608a
Revises: 79dd5b53753a
Create Date: 2023-08-21 23:38:30.747620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4fc0e4608a'
down_revision = '79dd5b53753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('cart_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('cart_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
