"""empty message

Revision ID: 628da1e991e6
Revises: e3a959cbebff
Create Date: 2023-08-07 19:01:47.841715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628da1e991e6'
down_revision = 'e3a959cbebff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_details_fkey', type_='foreignkey')
        batch_op.drop_column('details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_details_fkey', 'order_details', ['details'], ['id'])

    # ### end Alembic commands ###
