"""empty message

Revision ID: 79dd5b53753a
Revises: 843d70586138
Create Date: 2023-08-20 22:11:31.679349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dd5b53753a'
down_revision = '843d70586138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('recipient_last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_last_name', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
