"""empty message

Revision ID: 843d70586138
Revises: 2b9be79304a1
Create Date: 2023-08-20 22:10:36.568201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843d70586138'
down_revision = '2b9be79304a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('division')

    # ### end Alembic commands ###
