"""empty message

Revision ID: 954152d1c4c4
Revises: 628da1e991e6
Create Date: 2023-08-07 20:46:48.847397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954152d1c4c4'
down_revision = '628da1e991e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('tax_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('discount_id', sa.BigInteger(), nullable=True))
        batch_op.drop_constraint('products_tax_fkey', type_='foreignkey')
        batch_op.drop_constraint('products_currency_fkey', type_='foreignkey')
        batch_op.drop_constraint('products_discount_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'currencies', ['currency_id'], ['id'])
        batch_op.create_foreign_key(None, 'taxes', ['tax_id'], ['id'])
        batch_op.create_foreign_key(None, 'discounts', ['discount_id'], ['id'])
        batch_op.drop_column('tax')
        batch_op.drop_column('currency')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currency', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tax', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_discount_fkey', 'discounts', ['discount'], ['id'])
        batch_op.create_foreign_key('products_currency_fkey', 'currencies', ['currency'], ['id'])
        batch_op.create_foreign_key('products_tax_fkey', 'taxes', ['tax'], ['id'])
        batch_op.drop_column('discount_id')
        batch_op.drop_column('tax_id')
        batch_op.drop_column('currency_id')

    # ### end Alembic commands ###
