"""empty message

Revision ID: d54651ce554f
Revises: 82407c0bc2f4
Create Date: 2023-09-02 19:40:31.800257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54651ce554f'
down_revision = '82407c0bc2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
