"""empty message

Revision ID: e3a959cbebff
Revises: e6a00ac69383
Create Date: 2023-08-07 18:57:00.528864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a959cbebff'
down_revision = 'e6a00ac69383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.BigInteger(), nullable=True))
        batch_op.create_foreign_key(None, 'orders', ['order'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
