"""empty message

Revision ID: e6a00ac69383
Revises: 36eb0d17d962
Create Date: 2023-08-07 18:07:55.780600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a00ac69383'
down_revision = '36eb0d17d962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint('product_category_category_fkey', type_='foreignkey')
        batch_op.drop_constraint('product_category_product_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('category')
        batch_op.drop_column('product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('product_category_product_fkey', 'products', ['product'], ['id'])
        batch_op.create_foreign_key('product_category_category_fkey', 'categories', ['category'], ['id'])
        batch_op.drop_column('category_id')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
